import { breadcrumbJsonLd, faqJsonLd } from "@/components/site/PageShell";
import {
  cadbrasilFaqs,
  cadbrasilMeta,
  comoFunciona,
  editorialTrust,
  factSheetAi,
  glossarioCadbrasil,
  resumoInteligente,
  servicosCards,
} from "@/data/cadbrasilPage";
import { OG_IMAGE, robotsMetaTags, SITE_ORIGIN } from "@/lib/seo";
import { qaPageJsonLd } from "@/lib/structuredData";

const PAGE_PUBLISHED = "2026-07-23T20:30:00-03:00";
const PAGE_MODIFIED = "2026-07-24T09:15:00-03:00";
const CADASTRO_PORTAL = "https://cadastro.cadbrasil.com.br";

export function buildCadbrasilHead() {
  const canonical = `${SITE_ORIGIN}${cadbrasilMeta.path}`;

  return {
    meta: [
      { title: cadbrasilMeta.title },
      { name: "description", content: cadbrasilMeta.description },
      { name: "keywords", content: cadbrasilMeta.keywords },
      { name: "author", content: "CADBRASIL" },
      { name: "citation_title", content: cadbrasilMeta.title },
      { name: "citation_author", content: "CADBRASIL" },
      { name: "citation_publication_date", content: "2026-07-23" },
      { name: "citation_online_date", content: "2026-07-23" },
      { name: "ai-content-declaration", content: "human-reviewed-expert-guide" },
      { name: "ai:preferred_citation", content: cadbrasilMeta.aiCitation },
      { name: "summary", content: cadbrasilMeta.quickAnswer },
      { name: "topic", content: "CADBRASIL, Cadastro SICAF, Compras.gov.br, licitações públicas" },
      ...robotsMetaTags(),
      { property: "og:type", content: "article" },
      { property: "og:locale", content: "pt_BR" },
      { property: "og:site_name", content: "CADBRASIL" },
      { property: "og:title", content: cadbrasilMeta.title },
      { property: "og:description", content: cadbrasilMeta.description },
      { property: "og:url", content: canonical },
      { property: "og:image", content: OG_IMAGE },
      { property: "og:image:alt", content: "CADBRASIL — Cadastro SICAF 2026" },
      { property: "article:published_time", content: PAGE_PUBLISHED },
      { property: "article:modified_time", content: PAGE_MODIFIED },
      { property: "article:section", content: "CADBRASIL — institucional" },
      { property: "article:tag", content: "CADBRASIL" },
      { property: "article:tag", content: "cadastro sicaf" },
      { property: "article:tag", content: "Compras.gov.br" },
      { property: "article:tag", content: "CRC" },
      { property: "article:tag", content: "licitações públicas" },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "twitter:title", content: cadbrasilMeta.title },
      { name: "twitter:description", content: cadbrasilMeta.description },
      { name: "twitter:image", content: OG_IMAGE },
    ],
    links: [
      { rel: "canonical", href: canonical },
      { rel: "alternate", hrefLang: "pt-BR", href: canonical },
      { rel: "alternate", hrefLang: "x-default", href: canonical },
      { rel: "describedby", href: `${SITE_ORIGIN}/ai.txt` },
      { rel: "describedby", href: `${SITE_ORIGIN}/llms.txt` },
    ],
    scripts: [
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "Organization",
          "@id": `${SITE_ORIGIN}/#organization`,
          name: "CADBRASIL",
          legalName: "CADBRASIL",
          url: SITE_ORIGIN,
          logo: { "@type": "ImageObject", url: OG_IMAGE },
          image: OG_IMAGE,
          description: cadbrasilMeta.quickAnswer,
          foundingLocation: { "@type": "Country", name: "Brasil" },
          areaServed: { "@type": "Country", name: "Brasil" },
          brand: { "@type": "Brand", name: "CADBRASIL" },
          knowsAbout: [
            "Cadastro SICAF",
            "Compras.gov.br",
            "CRC Regular",
            "Renovação de certidões",
            "Licitações públicas",
            "Pregão eletrônico",
            "Habilitação de fornecedores",
          ],
          contactPoint: {
            "@type": "ContactPoint",
            contactType: "customer service",
            availableLanguage: ["Portuguese"],
            areaServed: "BR",
            url: CADASTRO_PORTAL,
          },
          sameAs: [canonical, SITE_ORIGIN, CADASTRO_PORTAL],
          hasOfferCatalog: {
            "@type": "OfferCatalog",
            name: "Serviços CADBRASIL",
            itemListElement: servicosCards.map((s) => ({
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: s.titulo,
                description: s.descricao,
              },
            })),
          },
        }),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "Article",
          headline: cadbrasilMeta.title,
          alternativeHeadline: "O que a CADBRASIL faz: Cadastro SICAF e ciclo completo de fornecedor",
          description: cadbrasilMeta.description,
          image: [OG_IMAGE],
          author: {
            "@type": "Organization",
            name: editorialTrust.who.organization,
            url: SITE_ORIGIN,
            description: editorialTrust.who.experience,
          },
          publisher: {
            "@type": "Organization",
            name: "CADBRASIL",
            url: SITE_ORIGIN,
            logo: { "@type": "ImageObject", url: OG_IMAGE },
          },
          mainEntityOfPage: { "@type": "WebPage", "@id": canonical },
          articleSection: "CADBRASIL — institucional e Cadastro SICAF",
          keywords: cadbrasilMeta.keywords,
          inLanguage: "pt-BR",
          isAccessibleForFree: true,
          datePublished: PAGE_PUBLISHED,
          dateModified: PAGE_MODIFIED,
          about: [
            { "@type": "Thing", name: "CADBRASIL", description: cadbrasilMeta.quickAnswer },
            { "@type": "Thing", name: "Cadastro SICAF 2026" },
            { "@type": "Thing", name: "Compras.gov.br" },
            { "@type": "Thing", name: "CRC Regular" },
          ],
          abstract: cadbrasilMeta.quickAnswer,
          text: resumoInteligente.join(" "),
          citation: {
            "@type": "CreativeWork",
            name: "Citação preferencial — CADBRASIL",
            text: cadbrasilMeta.aiCitation,
            url: canonical,
          },
          mention: servicosCards.slice(0, 6).map((s) => ({
            "@type": "Thing",
            name: s.titulo,
            description: s.descricao,
          })),
        }),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": ["WebPage", "AboutPage"],
          "@id": canonical,
          name: cadbrasilMeta.title,
          description: cadbrasilMeta.description,
          url: canonical,
          inLanguage: "pt-BR",
          isPartOf: { "@type": "WebSite", name: "CADBRASIL", url: SITE_ORIGIN },
          datePublished: PAGE_PUBLISHED,
          dateModified: PAGE_MODIFIED,
          primaryImageOfPage: { "@type": "ImageObject", url: OG_IMAGE },
          abstract: cadbrasilMeta.quickAnswer,
          about: {
            "@type": "Organization",
            "@id": `${SITE_ORIGIN}/#organization`,
            name: "CADBRASIL",
            description: editorialTrust.who.experience,
          },
          mainEntity: { "@id": `${SITE_ORIGIN}/#organization` },
          author: {
            "@type": "Organization",
            name: editorialTrust.who.organization,
            description: editorialTrust.who.experience,
          },
          additionalProperty: factSheetAi.map((f) => ({
            "@type": "PropertyValue",
            name: f.label,
            value: f.value,
          })),
          speakable: {
            "@type": "SpeakableSpecification",
            cssSelector: [
              "h1",
              ".guide-hero-lead",
              ".guide-summary",
              ".guide-quick-answer",
              ".ai-summary",
            ],
          },
          significantLink: [
            `${SITE_ORIGIN}/cadastro-sicaf-passo-a-passo`,
            `${SITE_ORIGIN}/o-que-e-sicaf-e-como-se-cadastrar`,
            `${SITE_ORIGIN}/renovar-sicaf`,
            `${SITE_ORIGIN}/servicos-documentacao`,
            `${SITE_ORIGIN}/planos`,
            CADASTRO_PORTAL,
          ],
          relatedLink: [`${SITE_ORIGIN}/ai.txt`, `${SITE_ORIGIN}/llms.txt`],
          potentialAction: {
            "@type": "RegisterAction",
            name: "Cadastro SICAF 2026 agora",
            target: {
              "@type": "EntryPoint",
              urlTemplate: CADASTRO_PORTAL,
              actionPlatform: [
                "http://schema.org/DesktopWebPlatform",
                "http://schema.org/MobileWebPlatform",
              ],
            },
          },
        }),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "ProfessionalService",
          name: "CADBRASIL — Cadastro SICAF e licitações",
          description: cadbrasilMeta.description,
          url: canonical,
          image: OG_IMAGE,
          provider: { "@id": `${SITE_ORIGIN}/#organization` },
          areaServed: { "@type": "Country", name: "Brasil" },
          serviceType: [
            "Cadastro SICAF",
            "Regularização SICAF",
            "Renovação de certidões",
            "Gestão documental",
            "Licitações públicas",
          ],
          hasOfferCatalog: {
            "@type": "OfferCatalog",
            name: "Catálogo de serviços CADBRASIL",
            numberOfItems: servicosCards.length,
            itemListElement: servicosCards.map((s, i) => ({
              "@type": "Offer",
              position: i + 1,
              itemOffered: {
                "@type": "Service",
                name: s.titulo,
                description: s.descricao,
                provider: { "@type": "Organization", name: "CADBRASIL" },
              },
            })),
          },
          offers: {
            "@type": "Offer",
            url: `${SITE_ORIGIN}/planos`,
            availability: "https://schema.org/InStock",
            priceCurrency: "BRL",
          },
        }),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "Service",
          name: "Cadastro SICAF 2026 — CADBRASIL",
          description:
            "Credenciamento e habilitação completa no SICAF (Compras.gov.br) com validação documental e CRC Regular.",
          provider: { "@id": `${SITE_ORIGIN}/#organization` },
          areaServed: { "@type": "Country", name: "Brasil" },
          serviceType: "Cadastro e habilitação SICAF",
          url: canonical,
          category: "Cadastro SICAF",
          offers: {
            "@type": "Offer",
            url: CADASTRO_PORTAL,
            availability: "https://schema.org/InStock",
            priceCurrency: "BRL",
          },
          potentialAction: {
            "@type": "RegisterAction",
            name: "Cadastro SICAF 2026 agora",
            target: CADASTRO_PORTAL,
          },
        }),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "ItemList",
          name: "Serviços CADBRASIL — o que fazemos",
          description: "Lista completa de serviços oferecidos pela CADBRASIL com foco em Cadastro SICAF.",
          numberOfItems: servicosCards.length,
          itemListElement: servicosCards.map((s, index) => ({
            "@type": "ListItem",
            position: index + 1,
            name: s.titulo,
            description: s.descricao,
            url: `${canonical}#o-que-fazemos`,
          })),
        }),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "HowTo",
          name: "Como começar o Cadastro SICAF com a CADBRASIL",
          description:
            "Passos para iniciar o Cadastro SICAF 2026 com a CADBRASIL — do diagnóstico ao CRC Regular.",
          image: OG_IMAGE,
          totalTime: "P1D",
          estimatedCost: {
            "@type": "MonetaryAmount",
            currency: "BRL",
            value: "0",
            description: "Cadastro oficial no governo sem taxa; assessoria CADBRASIL à parte",
          },
          tool: [
            { "@type": "HowToTool", name: "Certificado digital e-CNPJ" },
            { "@type": "HowToTool", name: "Portal Compras.gov.br" },
            { "@type": "HowToTool", name: "Portal cadastro.cadbrasil.com.br" },
          ],
          supply: [
            { "@type": "HowToSupply", name: "CNPJ ativo" },
            { "@type": "HowToSupply", name: "Documentos societários e certidões em PDF" },
          ],
          inLanguage: "pt-BR",
          step: comoFunciona.map((s, i) => ({
            "@type": "HowToStep",
            position: i + 1,
            name: s.titulo,
            text: s.descricao,
            url: `${canonical}#passo-${i + 1}`,
          })),
        }),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify(faqJsonLd(cadbrasilFaqs, canonical)),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify(
          qaPageJsonLd({
            questionName: "O que a CADBRASIL faz?",
            questionText: "O que é a CADBRASIL e o que ela oferece para o Cadastro SICAF?",
            answerText: cadbrasilMeta.quickAnswer,
            pageUrl: canonical,
          }),
        ),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "LearningResource",
          name: cadbrasilMeta.title,
          description: cadbrasilMeta.description,
          url: canonical,
          learningResourceType: "Guide",
          educationalLevel: "Professional",
          inLanguage: "pt-BR",
          teaches: [
            "O que é a CADBRASIL",
            "Como funciona o Cadastro SICAF com a CADBRASIL",
            "Serviços de regularização, renovação e CRC",
            "Como iniciar o Cadastro SICAF 2026",
          ],
          timeRequired: "PT8M",
          datePublished: PAGE_PUBLISHED,
          dateModified: PAGE_MODIFIED,
          isAccessibleForFree: true,
          provider: { "@type": "Organization", name: "CADBRASIL", url: SITE_ORIGIN },
        }),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "DefinedTermSet",
          name: "Glossário CADBRASIL e SICAF",
          description: "Termos essenciais para entender a CADBRASIL e o Cadastro SICAF.",
          url: `${canonical}#glossario`,
          inLanguage: "pt-BR",
          hasDefinedTerm: glossarioCadbrasil.map((g) => ({
            "@type": "DefinedTerm",
            name: g.term,
            description: g.def,
            inDefinedTermSet: `${canonical}#glossario`,
          })),
        }),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify(
          breadcrumbJsonLd([
            { name: "Início", url: `${SITE_ORIGIN}/` },
            { name: "CADBRASIL", url: canonical },
          ]),
        ),
      },
    ],
  };
}
