/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SicafDigitalRouteImport } from './routes/sicaf-digital'
import { Route as SicafCadastroUnificadoDeFornecedoresRouteImport } from './routes/sicaf-cadastro-unificado-de-fornecedores'
import { Route as RenovacaoSicafRouteImport } from './routes/renovacao-sicaf'
import { Route as PlataformaDigitalRouteImport } from './routes/plataforma-digital'
import { Route as OQueESicafRouteImport } from './routes/o-que-e-sicaf'
import { Route as CredenciamentoSicafDigitalRouteImport } from './routes/credenciamento-sicaf-digital'
import { Route as CredenciamentoRouteImport } from './routes/credenciamento'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ComoFazerCadastroNoSicafRouteImport } from './routes/como-fazer-cadastro-no-sicaf'
import { Route as ComoCadastrarEmpresaSicafRouteImport } from './routes/como-cadastrar-empresa-sicaf'
import { Route as BeneficiosRouteImport } from './routes/beneficios'
import { Route as AutoatendimentoSicafRouteImport } from './routes/autoatendimento-sicaf'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqIndexRouteImport } from './routes/faq.index'
import { Route as GuiaCadastroSicafPassoPassoRouteImport } from './routes/guia/cadastro-sicaf-passo-passo'
import { Route as FaqSlugRouteImport } from './routes/faq.$slug'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SicafDigitalRoute = SicafDigitalRouteImport.update({
  id: '/sicaf-digital',
  path: '/sicaf-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const SicafCadastroUnificadoDeFornecedoresRoute =
  SicafCadastroUnificadoDeFornecedoresRouteImport.update({
    id: '/sicaf-cadastro-unificado-de-fornecedores',
    path: '/sicaf-cadastro-unificado-de-fornecedores',
    getParentRoute: () => rootRouteImport,
  } as any)
const RenovacaoSicafRoute = RenovacaoSicafRouteImport.update({
  id: '/renovacao-sicaf',
  path: '/renovacao-sicaf',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaDigitalRoute = PlataformaDigitalRouteImport.update({
  id: '/plataforma-digital',
  path: '/plataforma-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const OQueESicafRoute = OQueESicafRouteImport.update({
  id: '/o-que-e-sicaf',
  path: '/o-que-e-sicaf',
  getParentRoute: () => rootRouteImport,
} as any)
const CredenciamentoSicafDigitalRoute =
  CredenciamentoSicafDigitalRouteImport.update({
    id: '/credenciamento-sicaf-digital',
    path: '/credenciamento-sicaf-digital',
    getParentRoute: () => rootRouteImport,
  } as any)
const CredenciamentoRoute = CredenciamentoRouteImport.update({
  id: '/credenciamento',
  path: '/credenciamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFazerCadastroNoSicafRoute =
  ComoFazerCadastroNoSicafRouteImport.update({
    id: '/como-fazer-cadastro-no-sicaf',
    path: '/como-fazer-cadastro-no-sicaf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComoCadastrarEmpresaSicafRoute =
  ComoCadastrarEmpresaSicafRouteImport.update({
    id: '/como-cadastrar-empresa-sicaf',
    path: '/como-cadastrar-empresa-sicaf',
    getParentRoute: () => rootRouteImport,
  } as any)
const BeneficiosRoute = BeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoatendimentoSicafRoute = AutoatendimentoSicafRouteImport.update({
  id: '/autoatendimento-sicaf',
  path: '/autoatendimento-sicaf',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaCadastroSicafPassoPassoRoute =
  GuiaCadastroSicafPassoPassoRouteImport.update({
    id: '/guia/cadastro-sicaf-passo-passo',
    path: '/guia/cadastro-sicaf-passo-passo',
    getParentRoute: () => rootRouteImport,
  } as any)
const FaqSlugRoute = FaqSlugRouteImport.update({
  id: '/faq/$slug',
  path: '/faq/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/autoatendimento-sicaf': typeof AutoatendimentoSicafRoute
  '/beneficios': typeof BeneficiosRoute
  '/como-cadastrar-empresa-sicaf': typeof ComoCadastrarEmpresaSicafRoute
  '/como-fazer-cadastro-no-sicaf': typeof ComoFazerCadastroNoSicafRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/credenciamento': typeof CredenciamentoRoute
  '/credenciamento-sicaf-digital': typeof CredenciamentoSicafDigitalRoute
  '/o-que-e-sicaf': typeof OQueESicafRoute
  '/plataforma-digital': typeof PlataformaDigitalRoute
  '/renovacao-sicaf': typeof RenovacaoSicafRoute
  '/sicaf-cadastro-unificado-de-fornecedores': typeof SicafCadastroUnificadoDeFornecedoresRoute
  '/sicaf-digital': typeof SicafDigitalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/guia/cadastro-sicaf-passo-passo': typeof GuiaCadastroSicafPassoPassoRoute
  '/faq/': typeof FaqIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/autoatendimento-sicaf': typeof AutoatendimentoSicafRoute
  '/beneficios': typeof BeneficiosRoute
  '/como-cadastrar-empresa-sicaf': typeof ComoCadastrarEmpresaSicafRoute
  '/como-fazer-cadastro-no-sicaf': typeof ComoFazerCadastroNoSicafRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/credenciamento': typeof CredenciamentoRoute
  '/credenciamento-sicaf-digital': typeof CredenciamentoSicafDigitalRoute
  '/o-que-e-sicaf': typeof OQueESicafRoute
  '/plataforma-digital': typeof PlataformaDigitalRoute
  '/renovacao-sicaf': typeof RenovacaoSicafRoute
  '/sicaf-cadastro-unificado-de-fornecedores': typeof SicafCadastroUnificadoDeFornecedoresRoute
  '/sicaf-digital': typeof SicafDigitalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/guia/cadastro-sicaf-passo-passo': typeof GuiaCadastroSicafPassoPassoRoute
  '/faq': typeof FaqIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/autoatendimento-sicaf': typeof AutoatendimentoSicafRoute
  '/beneficios': typeof BeneficiosRoute
  '/como-cadastrar-empresa-sicaf': typeof ComoCadastrarEmpresaSicafRoute
  '/como-fazer-cadastro-no-sicaf': typeof ComoFazerCadastroNoSicafRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/credenciamento': typeof CredenciamentoRoute
  '/credenciamento-sicaf-digital': typeof CredenciamentoSicafDigitalRoute
  '/o-que-e-sicaf': typeof OQueESicafRoute
  '/plataforma-digital': typeof PlataformaDigitalRoute
  '/renovacao-sicaf': typeof RenovacaoSicafRoute
  '/sicaf-cadastro-unificado-de-fornecedores': typeof SicafCadastroUnificadoDeFornecedoresRoute
  '/sicaf-digital': typeof SicafDigitalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/guia/cadastro-sicaf-passo-passo': typeof GuiaCadastroSicafPassoPassoRoute
  '/faq/': typeof FaqIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/autoatendimento-sicaf'
    | '/beneficios'
    | '/como-cadastrar-empresa-sicaf'
    | '/como-fazer-cadastro-no-sicaf'
    | '/como-funciona'
    | '/credenciamento'
    | '/credenciamento-sicaf-digital'
    | '/o-que-e-sicaf'
    | '/plataforma-digital'
    | '/renovacao-sicaf'
    | '/sicaf-cadastro-unificado-de-fornecedores'
    | '/sicaf-digital'
    | '/sitemap.xml'
    | '/api/contact'
    | '/faq/$slug'
    | '/guia/cadastro-sicaf-passo-passo'
    | '/faq/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/autoatendimento-sicaf'
    | '/beneficios'
    | '/como-cadastrar-empresa-sicaf'
    | '/como-fazer-cadastro-no-sicaf'
    | '/como-funciona'
    | '/credenciamento'
    | '/credenciamento-sicaf-digital'
    | '/o-que-e-sicaf'
    | '/plataforma-digital'
    | '/renovacao-sicaf'
    | '/sicaf-cadastro-unificado-de-fornecedores'
    | '/sicaf-digital'
    | '/sitemap.xml'
    | '/api/contact'
    | '/faq/$slug'
    | '/guia/cadastro-sicaf-passo-passo'
    | '/faq'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/autoatendimento-sicaf'
    | '/beneficios'
    | '/como-cadastrar-empresa-sicaf'
    | '/como-fazer-cadastro-no-sicaf'
    | '/como-funciona'
    | '/credenciamento'
    | '/credenciamento-sicaf-digital'
    | '/o-que-e-sicaf'
    | '/plataforma-digital'
    | '/renovacao-sicaf'
    | '/sicaf-cadastro-unificado-de-fornecedores'
    | '/sicaf-digital'
    | '/sitemap.xml'
    | '/api/contact'
    | '/faq/$slug'
    | '/guia/cadastro-sicaf-passo-passo'
    | '/faq/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  AutoatendimentoSicafRoute: typeof AutoatendimentoSicafRoute
  BeneficiosRoute: typeof BeneficiosRoute
  ComoCadastrarEmpresaSicafRoute: typeof ComoCadastrarEmpresaSicafRoute
  ComoFazerCadastroNoSicafRoute: typeof ComoFazerCadastroNoSicafRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  CredenciamentoRoute: typeof CredenciamentoRoute
  CredenciamentoSicafDigitalRoute: typeof CredenciamentoSicafDigitalRoute
  OQueESicafRoute: typeof OQueESicafRoute
  PlataformaDigitalRoute: typeof PlataformaDigitalRoute
  RenovacaoSicafRoute: typeof RenovacaoSicafRoute
  SicafCadastroUnificadoDeFornecedoresRoute: typeof SicafCadastroUnificadoDeFornecedoresRoute
  SicafDigitalRoute: typeof SicafDigitalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiContactRoute: typeof ApiContactRoute
  FaqSlugRoute: typeof FaqSlugRoute
  GuiaCadastroSicafPassoPassoRoute: typeof GuiaCadastroSicafPassoPassoRoute
  FaqIndexRoute: typeof FaqIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sicaf-digital': {
      id: '/sicaf-digital'
      path: '/sicaf-digital'
      fullPath: '/sicaf-digital'
      preLoaderRoute: typeof SicafDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sicaf-cadastro-unificado-de-fornecedores': {
      id: '/sicaf-cadastro-unificado-de-fornecedores'
      path: '/sicaf-cadastro-unificado-de-fornecedores'
      fullPath: '/sicaf-cadastro-unificado-de-fornecedores'
      preLoaderRoute: typeof SicafCadastroUnificadoDeFornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovacao-sicaf': {
      id: '/renovacao-sicaf'
      path: '/renovacao-sicaf'
      fullPath: '/renovacao-sicaf'
      preLoaderRoute: typeof RenovacaoSicafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma-digital': {
      id: '/plataforma-digital'
      path: '/plataforma-digital'
      fullPath: '/plataforma-digital'
      preLoaderRoute: typeof PlataformaDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-que-e-sicaf': {
      id: '/o-que-e-sicaf'
      path: '/o-que-e-sicaf'
      fullPath: '/o-que-e-sicaf'
      preLoaderRoute: typeof OQueESicafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credenciamento-sicaf-digital': {
      id: '/credenciamento-sicaf-digital'
      path: '/credenciamento-sicaf-digital'
      fullPath: '/credenciamento-sicaf-digital'
      preLoaderRoute: typeof CredenciamentoSicafDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credenciamento': {
      id: '/credenciamento'
      path: '/credenciamento'
      fullPath: '/credenciamento'
      preLoaderRoute: typeof CredenciamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-fazer-cadastro-no-sicaf': {
      id: '/como-fazer-cadastro-no-sicaf'
      path: '/como-fazer-cadastro-no-sicaf'
      fullPath: '/como-fazer-cadastro-no-sicaf'
      preLoaderRoute: typeof ComoFazerCadastroNoSicafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-cadastrar-empresa-sicaf': {
      id: '/como-cadastrar-empresa-sicaf'
      path: '/como-cadastrar-empresa-sicaf'
      fullPath: '/como-cadastrar-empresa-sicaf'
      preLoaderRoute: typeof ComoCadastrarEmpresaSicafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios': {
      id: '/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof BeneficiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoatendimento-sicaf': {
      id: '/autoatendimento-sicaf'
      path: '/autoatendimento-sicaf'
      fullPath: '/autoatendimento-sicaf'
      preLoaderRoute: typeof AutoatendimentoSicafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/': {
      id: '/faq/'
      path: '/faq'
      fullPath: '/faq/'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/cadastro-sicaf-passo-passo': {
      id: '/guia/cadastro-sicaf-passo-passo'
      path: '/guia/cadastro-sicaf-passo-passo'
      fullPath: '/guia/cadastro-sicaf-passo-passo'
      preLoaderRoute: typeof GuiaCadastroSicafPassoPassoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/$slug': {
      id: '/faq/$slug'
      path: '/faq/$slug'
      fullPath: '/faq/$slug'
      preLoaderRoute: typeof FaqSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  AutoatendimentoSicafRoute: AutoatendimentoSicafRoute,
  BeneficiosRoute: BeneficiosRoute,
  ComoCadastrarEmpresaSicafRoute: ComoCadastrarEmpresaSicafRoute,
  ComoFazerCadastroNoSicafRoute: ComoFazerCadastroNoSicafRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  CredenciamentoRoute: CredenciamentoRoute,
  CredenciamentoSicafDigitalRoute: CredenciamentoSicafDigitalRoute,
  OQueESicafRoute: OQueESicafRoute,
  PlataformaDigitalRoute: PlataformaDigitalRoute,
  RenovacaoSicafRoute: RenovacaoSicafRoute,
  SicafCadastroUnificadoDeFornecedoresRoute:
    SicafCadastroUnificadoDeFornecedoresRoute,
  SicafDigitalRoute: SicafDigitalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiContactRoute: ApiContactRoute,
  FaqSlugRoute: FaqSlugRoute,
  GuiaCadastroSicafPassoPassoRoute: GuiaCadastroSicafPassoPassoRoute,
  FaqIndexRoute: FaqIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
