/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OQueESicafRouteImport } from './routes/o-que-e-sicaf'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as BeneficiosRouteImport } from './routes/beneficios'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqIndexRouteImport } from './routes/faq.index'
import { Route as FaqSlugRouteImport } from './routes/faq.$slug'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OQueESicafRoute = OQueESicafRouteImport.update({
  id: '/o-que-e-sicaf',
  path: '/o-que-e-sicaf',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosRoute = BeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqSlugRoute = FaqSlugRouteImport.update({
  id: '/faq/$slug',
  path: '/faq/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/beneficios': typeof BeneficiosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/o-que-e-sicaf': typeof OQueESicafRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/faq/': typeof FaqIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/beneficios': typeof BeneficiosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/o-que-e-sicaf': typeof OQueESicafRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/faq': typeof FaqIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/beneficios': typeof BeneficiosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/o-que-e-sicaf': typeof OQueESicafRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/faq/': typeof FaqIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/beneficios'
    | '/como-funciona'
    | '/o-que-e-sicaf'
    | '/sitemap.xml'
    | '/api/contact'
    | '/faq/$slug'
    | '/faq/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/beneficios'
    | '/como-funciona'
    | '/o-que-e-sicaf'
    | '/sitemap.xml'
    | '/api/contact'
    | '/faq/$slug'
    | '/faq'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/beneficios'
    | '/como-funciona'
    | '/o-que-e-sicaf'
    | '/sitemap.xml'
    | '/api/contact'
    | '/faq/$slug'
    | '/faq/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  BeneficiosRoute: typeof BeneficiosRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  OQueESicafRoute: typeof OQueESicafRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiContactRoute: typeof ApiContactRoute
  FaqSlugRoute: typeof FaqSlugRoute
  FaqIndexRoute: typeof FaqIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-que-e-sicaf': {
      id: '/o-que-e-sicaf'
      path: '/o-que-e-sicaf'
      fullPath: '/o-que-e-sicaf'
      preLoaderRoute: typeof OQueESicafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios': {
      id: '/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof BeneficiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/': {
      id: '/faq/'
      path: '/faq'
      fullPath: '/faq/'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/$slug': {
      id: '/faq/$slug'
      path: '/faq/$slug'
      fullPath: '/faq/$slug'
      preLoaderRoute: typeof FaqSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  BeneficiosRoute: BeneficiosRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  OQueESicafRoute: OQueESicafRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiContactRoute: ApiContactRoute,
  FaqSlugRoute: FaqSlugRoute,
  FaqIndexRoute: FaqIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
